<main>
	<div class="homebanner">
		<div id="homebannerslides">
			<slideshow id="slideshowid" width="1500" height="1028" path="SlideShows/Home Page"></slideshow>
		</div><div class="clear"></div>
	</div>
	<div class="grid-container">
		<div class="grid-50 tablet-grid-50">
			<a href="/living-room.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner1.jpg" width="590" height="222" alt="Living Room" />
							<div class="banneroverlay">
								<h2>Living Room</h2>
								<p>Sit Back and Relax</p>
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
		<div class="grid-50 tablet-grid-50">
			<a href="/dining-room.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner2.jpg" width="590" height="222" alt="Dining Room" />
							<div class="banneroverlay">
								<h2>Dining Room</h2>
								<p>Eat and Gather</p>
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div><div class="clear"></div>
		<div class="grid-50 tablet-grid-50">
			<a href="/bedroom.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner3.jpg" width="590" height="222" alt="Bedroom" />
							<div class="banneroverlay">
								<h2>Bedroom</h2>
								<p>Make Sleeping Comfortable</p>
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
		<div class="grid-50 tablet-grid-50">
			<a href="/entertainment.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner4.jpg" width="590" height="222" alt="Entertainment" />
							<div class="banneroverlay">
								<h2>Entertainment</h2>
								<p>Play and Enjoy</p>
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div><div class="clear"></div>
		<div class="grid-50 tablet-grid-50">
			<a href="/home-office.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner5.jpg" width="590" height="222" alt="Home Office" />
							<div class="banneroverlay">
								<h2>Home Office</h2>
								<p>Work and Study</p>
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
		<div class="grid-50 tablet-grid-50">
			<a href="/accessories.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner6.jpg" width="590" height="222" alt="Accessories" />
							<div class="banneroverlay">
								<h2>Accessories</h2>
								<p>Accessorized</p>
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div><div class="clear"></div>
		<div class="grid-33 tablet-grid-33">
			<div class="subbannertitle">
				<p>Every Day Values</p>
			</div>
			<a href="/displayflyer.aspx">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner7.jpg" width="382" height="252" alt="Promotions" />
							<div class="banneroverlay leftbanner">
								<p class="bannerbutton">View</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
		<div class="grid-33 tablet-grid-33">
			<div class="subbannertitle">
				<p>Design Center</p>
			</div>
			<a href="/design-center.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner8.jpg" width="382" height="252" alt="Design Center" />
							<div class="banneroverlay middlebanner">
								<p class="bannerbutton">Get Inspired</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
		<div class="grid-33 tablet-grid-33">
			<div class="subbannertitle">
				<p>Plan Your Room</p>
			</div>
			<a href="/room-planner.inc">
				<div class="subbanner">
					<div class="staticbox-black">
						<div class="subbannerimg">
							<img src="/css/20126/images/homebanner9.jpg" width="382" height="252" alt="Room Planner" />
							<div class="banneroverlay rightbanner">
								<p class="bannerbutton">Start Planning</p>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div><div class="clear"></div>
		<div class="grid-30 tablet-grid-30">
			<div class="homevideo">
				<img src="/css/20126/images/homevideo.jpg" width="340" height="267" alt="Video Placeholder" />
			</div>
		</div>
		<div class="grid-70 tablet-grid-70">
			<div class="homepagetext">
				<h1>MICROD</h1>
				<p>MD Furniture in Charlotte, NC has earned a reputation for providing quality furniture for less since 1927. We are a full service home furniture store including Free in-home design services, free delivery and free financing. At MD Furniture we carry a complete line up of home furniture including Living Rooms, Dining rooms, Bedrooms, Home Office, Entertainment, Mattresses, Out Door Furniture and bedding, Youth Bedroom, and family rooms. We offer a "good, better, best" price range in all of these categories. The advantage we have as an independent family owned furniture store is that we can choose from thousands of suppliers to find the best furniture for your home. We carefully research our furniture manufacturers at international trade shows several times a year to make sure that we are picking the companies that offer the best value in the furniture industry.</p>
			</div>
		</div><div class="clear"></div>
		<div class="grid-100">
			<div class="homebrandstitle">
				<p>Brands We Carry</p>
			</div>
			<div class="brandslider">
				<AttributeList id="Brand" class="BrandLogos" ListAttribute="Brand" ItemType="item" Thumbnail="Yes" />
				<script type="text/javascript">
					$(document).ready(function() {
					  $("#Brand").owlCarousel({
						  items : 6, //10 items above 1000px browser width
							itemsDesktop : [1000,5], //5 items between 1000px and 901px
							itemsDesktopSmall : [900,3], // betweem 900px and 601px
							itemsTablet: [600,2], //2 items between 600 and 0
							navigation:false
					  });
					});
				</script>
			</div><div class="clear"></div>
		</div>
	</div><div class="clear"></div>
</main>